# Generated by Django 6.0.5 on 2026-06-05 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartoes', '0001_initial'),
        ('vinculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('parcelamento_cartao', 'Parcelamento no cartão'), ('financiamento', 'Financiamento'), ('emprestimo', 'Empréstimo'), ('informal', 'Dívida informal')], max_length=20, verbose_name='tipo')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor total')),
                ('numero_parcelas', models.PositiveSmallIntegerField(verbose_name='número de parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor da parcela')),
                ('parcela_inicial', models.PositiveSmallIntegerField(default=1, verbose_name='parcela inicial')),
                ('data_primeira_parcela', models.DateField(verbose_name='data da primeira parcela')),
                ('juros', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='juros (%)')),
                ('compartilhado', models.BooleanField(default=False, verbose_name='compartilhado')),
                ('valor_dono', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor do dono')),
                ('valor_vinculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor do vinculado')),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dividas', to='cartoes.cartao', verbose_name='cartão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividas', to='vinculos.vinculo', verbose_name='vínculo')),
            ],
            options={
                'verbose_name': 'dívida',
                'verbose_name_plural': 'dívidas',
                'ordering': ['-data_primeira_parcela', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='número')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('mes_referencia', models.DateField(verbose_name='mês de referência')),
                ('data_vencimento', models.DateField(verbose_name='data de vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga')], default='pendente', max_length=10, verbose_name='status')),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='dividas.divida', verbose_name='dívida')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas', to='cartoes.fatura', verbose_name='fatura')),
            ],
            options={
                'verbose_name': 'parcela',
                'verbose_name_plural': 'parcelas',
                'ordering': ['divida', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('divida', 'numero'), name='parcela_unica_por_divida')],
            },
        ),
    ]
