# Generated by Django 6.0.5 on 2026-06-05 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('imovel', 'Imóvel'), ('veiculo', 'Veículo'), ('outro', 'Outro')], max_length=20, verbose_name='tipo')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor estimado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'bem',
                'verbose_name_plural': 'bens',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatrimonioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('mes_referencia', models.DateField(verbose_name='mês de referência')),
                ('total_ativos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total de ativos')),
                ('total_passivos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total de passivos')),
                ('patrimonio_liquido', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='patrimônio líquido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'snapshot de patrimônio',
                'verbose_name_plural': 'snapshots de patrimônio',
                'ordering': ['mes_referencia'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'mes_referencia'), name='patrimonio_snapshot_unico_por_mes')],
            },
        ),
    ]
