# Generated by Django 6.0.5 on 2026-06-05 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('renda_fixa', 'Renda fixa'), ('acoes', 'Ações'), ('fiis', 'FIIs'), ('cripto', 'Cripto'), ('tesouro', 'Tesouro'), ('poupanca', 'Poupança'), ('outro', 'Outro')], max_length=20, verbose_name='tipo')),
                ('instituicao', models.CharField(blank=True, max_length=80, null=True, verbose_name='instituição')),
                ('descricao', models.CharField(blank=True, max_length=120, null=True, verbose_name='descrição')),
                ('valor_aportado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor aportado')),
                ('data_aporte', models.DateField(verbose_name='data do aporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'investimento',
                'verbose_name_plural': 'investimentos',
                'ordering': ['-data_aporte', '-id'],
            },
        ),
    ]
