# Generated by Django 6.0.5 on 2026-06-05 12:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartoes', '0001_initial'),
        ('categorias', '0001_initial'),
        ('vinculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('A', 'Tipo A — fixo'), ('B', 'Tipo B — estimado')], max_length=1, verbose_name='tipo')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor estimado')),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='dia de vencimento')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('cartao', 'Cartão'), ('debito', 'Débito'), ('pix', 'Pix'), ('boleto', 'Boleto')], max_length=15, null=True, verbose_name='forma de pagamento')),
                ('compartilhado', models.BooleanField(default=False, verbose_name='compartilhado')),
                ('valor_dono', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor do dono')),
                ('valor_vinculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor do vinculado')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_fixos', to='cartoes.cartao', verbose_name='cartão')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_fixos', to='categorias.categoria', verbose_name='categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_fixos', to='vinculos.vinculo', verbose_name='vínculo')),
            ],
            options={
                'verbose_name': 'gasto fixo',
                'verbose_name_plural': 'gastos fixos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='GastoFixoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('mes_referencia', models.DateField(verbose_name='mês de referência')),
                ('valor_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor real')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], default='pendente', max_length=10, verbose_name='status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='check em')),
                ('gasto_fixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensais', to='gastos_fixos.gastofixo', verbose_name='gasto fixo')),
            ],
            options={
                'verbose_name': 'gasto fixo mensal',
                'verbose_name_plural': 'gastos fixos mensais',
                'ordering': ['-mes_referencia', 'gasto_fixo__descricao'],
                'constraints': [models.UniqueConstraint(fields=('gasto_fixo', 'mes_referencia'), name='gastofixomensal_unico_por_mes')],
            },
        ),
    ]
