# Generated by Django 6.0.5 on 2026-06-04 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=10, verbose_name='status')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceito em')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'vínculo',
                'verbose_name_plural': 'vínculos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('solicitante', 'destinatario'), name='vinculo_par_unico'), models.CheckConstraint(condition=models.Q(('solicitante', models.F('destinatario')), _negated=True), name='vinculo_sem_auto')],
            },
        ),
    ]
