# Generated by Django 6.0.5 on 2026-06-11 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0002_compradetalhada_itemcompra'),
        ('receitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoDetectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('recebido', 'Recebido'), ('enviado', 'Enviado')], max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor')),
                ('contraparte', models.CharField(blank=True, max_length=120, null=True, verbose_name='contraparte')),
                ('banco', models.CharField(blank=True, max_length=60, null=True, verbose_name='banco')),
                ('pacote', models.CharField(blank=True, max_length=120, null=True, verbose_name='pacote do app')),
                ('texto_bruto', models.TextField(verbose_name='texto da notificação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('ignorada', 'Ignorada')], default='pendente', max_length=12, verbose_name='status')),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gastos.gasto')),
                ('receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='receitas.receita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'movimentação detectada',
                'verbose_name_plural': 'movimentações detectadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
