# Generated by Django 6.0.5 on 2026-06-17 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='nome do arquivo')),
                ('formato', models.CharField(choices=[('ofx', 'OFX'), ('csv', 'CSV')], max_length=5, verbose_name='formato')),
                ('quantidade_transacoes', models.IntegerField(default=0, verbose_name='transações importadas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'importação',
                'verbose_name_plural': 'importações',
                'ordering': ['-created_at'],
            },
        ),
    ]
