# Generated by Django 6.0.5 on 2026-06-05 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartoes', '0001_initial'),
        ('categorias', '0001_initial'),
        ('vinculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('data', models.DateField(verbose_name='data')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Débito'), ('credito', 'Crédito')], max_length=15, verbose_name='forma de pagamento')),
                ('compartilhado', models.BooleanField(default=False, verbose_name='compartilhado')),
                ('valor_dono', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor do dono')),
                ('valor_vinculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor do vinculado')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR Code'), ('ocr', 'OCR')], default='manual', max_length=10, verbose_name='origem')),
                ('mes_referencia', models.DateField(verbose_name='mês de referência')),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='cartoes.cartao', verbose_name='cartão')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='categorias.categoria', verbose_name='categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='categorias.subcategoria', verbose_name='subcategoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='vinculos.vinculo', verbose_name='vínculo')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GastoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.gasto')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.tag')),
            ],
            options={
                'verbose_name': 'tag do gasto',
                'verbose_name_plural': 'tags do gasto',
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='gastos', through='gastos.GastoTag', to='categorias.tag', verbose_name='tags'),
        ),
        migrations.AddConstraint(
            model_name='gastotag',
            constraint=models.UniqueConstraint(fields=('gasto', 'tag'), name='gastotag_unico'),
        ),
    ]
