# Generated by Django 6.0.5 on 2026-06-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDetalhada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.CharField(blank=True, max_length=120, null=True, verbose_name='estabelecimento')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR Code'), ('ocr', 'OCR')], default='manual', max_length=10, verbose_name='origem')),
                ('url_nfce', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da NFC-e')),
                ('gasto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compra_detalhada', to='gastos.gasto', verbose_name='gasto')),
            ],
            options={
                'verbose_name': 'compra detalhada',
                'verbose_name_plural': 'compras detalhadas',
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('codigo', models.CharField(blank=True, max_length=40, null=True, verbose_name='código')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='quantidade')),
                ('unidade', models.CharField(blank=True, max_length=10, null=True, verbose_name='unidade')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor unitário')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('identificado', models.BooleanField(default=True, verbose_name='identificado')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_compra', to='categorias.categoria', verbose_name='categoria')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gastos.compradetalhada', verbose_name='compra')),
            ],
            options={
                'verbose_name': 'item de compra',
                'verbose_name_plural': 'itens de compra',
                'ordering': ['id'],
            },
        ),
    ]
