# Generated by Django 6.0.5 on 2026-06-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_compradetalhada_itemcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', verbose_name='comprovante'),
        ),
    ]
