# Generated by Django 6.0.5 on 2026-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_gasto_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='local_nome',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='nome do local'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
