# Generated by Django 6.0.5 on 2026-06-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='cor',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='cor'),
        ),
    ]
