# Generated by Django 6.0.5 on 2026-06-05 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vinculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('data_prevista', models.DateField(verbose_name='data prevista')),
                ('data_real', models.DateField(blank=True, null=True, verbose_name='data real')),
                ('tipo', models.CharField(choices=[('salario', 'Salário'), ('freelance', 'Freelance'), ('aluguel', 'Aluguel'), ('bonus', 'Bônus'), ('outro', 'Outro')], max_length=20, verbose_name='tipo')),
                ('recorrente', models.BooleanField(default=False, verbose_name='recorrente')),
                ('compartilhada', models.BooleanField(default=False, verbose_name='compartilhada')),
                ('valor_dono', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor do dono')),
                ('valor_vinculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor do vinculado')),
                ('mes_referencia', models.DateField(verbose_name='mês de referência')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='vinculos.vinculo', verbose_name='vínculo')),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
                'ordering': ['-data_prevista', '-id'],
            },
        ),
    ]
