# Generated by Django 6.0.5 on 2026-06-05 21:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor alvo')),
                ('valor_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor atual')),
                ('data_alvo', models.DateField(blank=True, null=True, verbose_name='data alvo')),
                ('contribuicao_mensal_planejada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='contribuição mensal planejada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AporteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('data', models.DateField(verbose_name='data')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='observação')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='metas.meta', verbose_name='meta')),
            ],
            options={
                'verbose_name': 'aporte de meta',
                'verbose_name_plural': 'aportes de meta',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
