# Generated by Django 6.0.5 on 2026-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='cor',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='meta',
            name='emoji',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='emoji'),
        ),
    ]
